// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PatioVeiculos.Infrastructure.Contexts;

#nullable disable

namespace PatioVeiculos.Infrastructure.Migrations
{
    [DbContext(typeof(PatioVeiculosContext))]
    partial class PatioVeiculosContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.12");

            modelBuilder.Entity("PatioVeiculos.Domain.Models.Movimentacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataHoraEntrada")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataHoraSaida")
                        .HasColumnType("TEXT");

                    b.Property<int>("PrecoHorasId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SessaoAberta")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("ValorCobrado")
                        .HasColumnType("TEXT");

                    b.Property<int>("VeiculoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PrecoHorasId");

                    b.HasIndex("VeiculoId");

                    b.ToTable("Movimentacoes");
                });

            modelBuilder.Entity("PatioVeiculos.Domain.Models.PrecoHoras", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AplicadoEm")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DemaisHoras")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrimeiraHora")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PrecosHoras");
                });

            modelBuilder.Entity("PatioVeiculos.Domain.Models.Veiculo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cor")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Placa")
                        .IsUnique();

                    b.ToTable("Veiculos");
                });

            modelBuilder.Entity("PatioVeiculos.Domain.Models.Movimentacao", b =>
                {
                    b.HasOne("PatioVeiculos.Domain.Models.PrecoHoras", "PrecoHoras")
                        .WithMany("Movimentacoes")
                        .HasForeignKey("PrecoHorasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PatioVeiculos.Domain.Models.Veiculo", "Veiculo")
                        .WithMany("Movimentacoes")
                        .HasForeignKey("VeiculoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PrecoHoras");

                    b.Navigation("Veiculo");
                });

            modelBuilder.Entity("PatioVeiculos.Domain.Models.PrecoHoras", b =>
                {
                    b.Navigation("Movimentacoes");
                });

            modelBuilder.Entity("PatioVeiculos.Domain.Models.Veiculo", b =>
                {
                    b.Navigation("Movimentacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
